scrape_configs:
  - job_name: 'spring-backend'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['backend:8080']
  
  - job_name: 'keycloak'
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['keycloak:8080']